server:
  port: 8085  # Avoids conflict with other services

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:h2:mem:authdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

  cloud:
    stream:
      bindings:
        userRegistered-out-0:
          destination: user-registered-topic
        userLoggedIn-out-0:
          destination: user-loggedin-topic
        loginEventHandler-in-0:
          destination: user-loggedin-topic
      kafka:
        binder:
          brokers: localhost:9092

logging:
  level:
    org.springframework.security: INFO
    org.apache.kafka: INFO
    com.travelbooking.userservice: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info