server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:authdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    stream:
      bindings:
        userRegistered-out-0:
          destination: user-registered-topic
        userLoggedIn-out-0:
          destination: user-loggedin-topic
        loginEventHandler-in-0:
          destination: user-loggedin-topic
      kafka:
        binder:
          brokers: localhost:9092